### ISSUE TITLE
Pattern Matching in wrong section?

### ISSUE THREAD

**Issue by Schinkikami** [sosiristseng/gensjulia#81]
Nice collection  thank you :)

I think SimpleMatch.jl, Match.jl and MLStyle.jl belong into the Programming Paradigms category and not Algorithms? As pattern matching is an essential programming style in functional programming langs (Haskell, Lisps etc.).

**Comment by sosiristseng** [comment]
Thank you are your comment. I'll move them to the appropriate sections.
